dataset_name: vessel
train_split: ['train']
val_split: ['validation']
test_split: ['test']
dataset: {
  json_file: ./data/vessel/annotations/vessel.json,
  feat_folder: ./data/vessel/image,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 2,
  input_dim: 4096,
  feat_stride: 4,
  num_frames: 4,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 128,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 4,
  SpAtten: True,
  TeAtten: True,
  SelfAtten: True,
  pretrain: True,
  random_patch: True,
}
opt: {
  learning_rate: 0.0001,
  epochs: 45,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
# the inference on THUMOS is quite different from EPIC-kitchens
# a major performance gain is achieved by fusing external classification scores
# doing so will require disable multiclass_nms and enable score fusion
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  multiclass_nms: False,
  # comment out L47-48 and uncomment L50 to disable score fusion
  # multiclass_nms: True,
}
output_folder: ./ckpt/
